//
// Created by lc on 2022/4/28.
//

#ifndef CPPGL_VERSION_HPP
#define CPPGL_VERSION_HPP

#ifndef CPPGL_GLFW_CONTEXT_VERSION_MAJOR
#define CPPGL_GLFW_CONTEXT_VERSION_MAJOR 3
#endif

#ifndef CPPGL_GLFW_CONTEXT_VERSION_MINOR
#define CPPGL_GLFW_CONTEXT_VERSION_MINOR 3
#endif

#endif //CPPGL_VERSION_HPP
